import {
  generateSeededUUIDs,
  getRandomIntInclusive,
} from 'src/utils/constants/seedFunctions';

const product_id_seed = 'product';
const number_of_products = 1000;
const product_ids = generateSeededUUIDs(product_id_seed, number_of_products);

const vendor_ids = [
  '8a7d3b5a-2d4e-4f6a-8a3e-7b6d5f3e5a6d',
  '6d3b4f5a-2e4d-4a7e-9b3d-8a3b5d3e5a7e',
  '5d4a7b3e-2f6d-4a3b-8e7d-9b6a5d4e3a7e',
  '4a7d3b5e-2d6e-4f8a-9b7d-8a3b5d6e4a7e',
  '9b3d5a7e-2e6d-4f8b-8a3e-7d6b5a3e4a7e',
];

const product_categories = [
  'T-shirts',
  'Jeans',
  'Dresses',
  'Shirts',
  'Tops',
  'Pants',
  'Coats',
  'Underwear',
];

const product_names = [
  'Classic Cotton Tee',
  'Slim Fit Jeans',
  'Summer Floral Dress',
  'Casual Button-Down Shirt',
  'Sleeveless Tank Top',
  'Chino Pants',
  'Winter Wool Coat',
  'Comfort Fit Boxer Briefs',
  'Graphic T-shirt',
  'High-Waisted Skinny Jeans',
  'Basic White T-shirt',
  'Graphic Print T-shirt',
  'Striped T-shirt',
  'V-neck T-shirt',
  'Long Sleeve T-shirt',
  'Pocket T-shirt',
  'Crew Neck T-shirt',
  'Oversized T-shirt',
  'Slim Fit T-shirt',
  'Sport T-shirt',
  'Skinny Jeans',
  'Straight Leg Jeans',
  'Bootcut Jeans',
  'High Waisted Jeans',
  'Distressed Jeans',
  'Boyfriend Jeans',
  'Stretch Jeans',
  'Flare Jeans',
  'Wide Leg Jeans',
  'Cropped Jeans',
  'Summer Dress',
  'Maxi Dress',
  'Midi Dress',
  'Mini Dress',
  'Wrap Dress',
  'Bodycon Dress',
  'A-line Dress',
  'Shift Dress',
  'Off-shoulder Dress',
  'Cocktail Dress',
  'Formal Shirt',
  'Casual Shirt',
  'Linen Shirt',
  'Denim Shirt',
  'Plaid Shirt',
  'Oxford Shirt',
  'Flannel Shirt',
  'Hawaiian Shirt',
  'Chambray Shirt',
  'Button Down Shirt',
  'Tank Top',
  'Crop Top',
  'Blouse Top',
  'Tube Top',
  'Peplum Top',
  'Camisole Top',
  'Halter Top',
  'Sleeveless Top',
  'Ruffle Top',
  'Wrap Top',
  'Chino Pants',
  'Cargo Pants',
  'Sweatpants',
  'Jogger Pants',
  'Dress Pants',
  'Khaki Pants',
  'Corduroy Pants',
  'Leggings',
  'Yoga Pants',
  'Wide Leg Pants',
  'Trench Coat',
  'Peacoat',
  'Parka Coat',
  'Bomber Jacket',
  'Denim Jacket',
  'Leather Jacket',
  'Raincoat',
  'Windbreaker',
  'Down Coat',
  'Wool Coat',
  'Boxer Shorts',
  'Briefs',
  'Trunks',
  'Boxer Briefs',
  'Bikini Underwear',
  'Thong Underwear',
  'Hipster Underwear',
  'Seamless Underwear',
  'High Waisted Underwear',
  'Lace Underwear',
  'Sweater',
  'Hoodie',
  'Cardigan',
  'Pullover',
  'Crew Neck Sweater',
  'V-neck Sweater',
  'Turtleneck Sweater',
  'Zipper Hoodie',
  'Open Front Cardigan',
  'Sweater Vest',
];

const lorem_string =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

const products = [];
for (let i = 0; i < product_ids.length; i++) {
  const product = {
    id: product_ids[i],
    vendor_id: vendor_ids[getRandomIntInclusive(0, 4)],
    product_name: product_names[getRandomIntInclusive(0, 99)],
    description: lorem_string,
    quantity: 1000,
    price: getRandomIntInclusive(1, 1000),
    category: product_categories[getRandomIntInclusive(0, 7)],
    created_at: '2022-01-01',
  };
  products.push(product);
}

export { products };
