import { EUserRole } from 'src/common/enums/user-role.enum';
import { EUserStatus } from 'src/common/enums/user-status.enum';

export const users = [
  {
    id: '8a6e0804-2bd0-4672-b79d-d97027f9071a',
    full_name: 'John Doe',
    email: 'john.doe@example.com',
    password: 'password123',
    created_at: '2024-04-04',
    updated_at: '2024-04-04',
    is_verified: true,
    filled_profile_step: 0,
    otp_code: null,
    user_status: EUserStatus.REGISTRATION,
    is_deleted_by_admin: false,
    user_role: null,
    avatar: null,
    phone: null,
    address: null,
    address_2: null,
    country: null,
    state: null,
    city: null,
    cloth_size: null,
    jeans_size: null,
    shoes_size: null,
    stripe_id: null,
    payment_method_id: null,
  },
  {
    id: '1',
    created_at: new Date('2023-01-01T00:00:00Z'),
    updated_at: new Date('2023-01-01T00:00:00Z'),
    stripe_id: null,
    payment_method_id: null,
    full_name: 'Jane Smith',
    email: 'jane.smith@example.com',
    password: 'password123',
    is_verified: true,
    filled_profile_step: 2,
    otp_code: '123456',
    user_status: EUserStatus.ACTIVE,
    is_deleted_by_admin: false,
    user_role: EUserRole.BUYER,
    avatar: null,
    phone: '0987654321',
    address: '456 Elm St',
    address_2: null,
    country: 'Canada',
    city: 'Los Angeles',
    cloth_size: 'S',
    jeans_size: 'M',
    shoes_size: 8,
  },
  {
    id: '2',
    created_at: new Date('2023-01-02T00:00:00Z'),
    updated_at: new Date('2023-01-02T00:00:00Z'),
    stripe_id: null,
    payment_method_id: null,
    full_name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    password: 'password123',
    is_verified: true,
    filled_profile_step: 3,
    otp_code: '654321',
    user_status: EUserStatus.ACTIVE,
    is_deleted_by_admin: false,
    user_role: EUserRole.VENDOR,
    avatar: null,
    phone: '1122334455',
    address: '789 Oak St',
    address_2: null,
    country: 'Canada',
    city: 'Toronto',
    cloth_size: 'L',
    jeans_size: 'L',
    shoes_size: 9,
  },
  {
    id: '3',
    created_at: new Date('2023-01-03T00:00:00Z'),
    updated_at: new Date('2023-01-03T00:00:00Z'),
    stripe_id: null,
    payment_method_id: null,
    full_name: 'Bob Brown',
    email: 'bob.brown@example.com',
    password: 'password123',
    is_verified: true,
    filled_profile_step: 5,
    otp_code: null,
    user_status: EUserStatus.ACTIVE,
    is_deleted_by_admin: false,
    user_role: EUserRole.BUYER,
    avatar: null,
    phone: '2233445566',
    address: '101 Pine St',
    address_2: null,
    country: 'Canada',
    city: 'London',
    cloth_size: 'XL',
    jeans_size: 'XL',
    shoes_size: 11,
  },
  {
    id: '4',
    created_at: new Date('2023-01-04T00:00:00Z'),
    updated_at: new Date('2023-01-04T00:00:00Z'),
    stripe_id: null,
    payment_method_id: null,
    full_name: 'Charlie Green',
    email: 'charlie.green@example.com',
    password: 'password123',
    is_verified: true,
    filled_profile_step: 5,
    otp_code: '789012',
    user_status: EUserStatus.ACTIVE,
    is_deleted_by_admin: false,
    user_role: EUserRole.VENDOR,
    avatar: null,
    phone: '3344556677',
    address: '202 Cedar St',
    address_2: null,
    country: 'Canada',
    city: 'Sydney',
    cloth_size: 'M',
    jeans_size: 'M',
    shoes_size: 10,
  },
  {
    id: '5',
    created_at: new Date('2023-01-05T00:00:00Z'),
    updated_at: new Date('2023-01-05T00:00:00Z'),
    stripe_id: null,
    payment_method_id: null,
    full_name: 'David Wilson',
    email: 'david.wilson@example.com',
    password: 'password123',
    is_verified: true,
    filled_profile_step: 5,
    otp_code: null,
    user_status: EUserStatus.ACTIVE,
    is_deleted_by_admin: false,
    user_role: EUserRole.BUYER,
    avatar: null,
    phone: '4455667788',
    address: '303 Birch St',
    address_2: null,
    country: 'Canada',
    city: 'Chicago',
    cloth_size: 'L',
    jeans_size: 'L',
    shoes_size: 9,
  },
  {
    id: '6',
    created_at: new Date('2023-01-06T00:00:00Z'),
    updated_at: new Date('2023-01-06T00:00:00Z'),
    stripe_id: null,
    payment_method_id: null,
    full_name: 'Eve Davis',
    email: 'eve.davis@example.com',
    password: 'password123',
    is_verified: true,
    filled_profile_step: 5,
    otp_code: '210987',
    user_status: EUserStatus.ACTIVE,
    is_deleted_by_admin: false,
    user_role: EUserRole.BUYER,
    avatar: null,
    phone: '5566778899',
    address: '404 Maple St',
    address_2: null,
    country: 'Canada',
    city: 'Berlin',
    cloth_size: 'S',
    jeans_size: 'S',
    shoes_size: 7,
  },
  {
    id: '7',
    created_at: new Date('2023-01-07T00:00:00Z'),
    updated_at: new Date('2023-01-07T00:00:00Z'),
    stripe_id: null,
    payment_method_id: null,
    full_name: 'Frank Miller',
    email: 'frank.miller@example.com',
    password: 'password123',
    is_verified: true,
    filled_profile_step: 3,
    otp_code: null,
    user_status: EUserStatus.ACTIVE,
    is_deleted_by_admin: false,
    user_role: EUserRole.VENDOR,
    avatar: null,
    phone: '6677889900',
    address: '505 Walnut St',
    address_2: null,
    country: 'Canada',
    city: 'Paris',
    cloth_size: 'XL',
    jeans_size: 'XL',
    shoes_size: 9,
  },
  {
    id: '8',
    created_at: new Date('2023-01-08T00:00:00Z'),
    updated_at: new Date('2023-01-08T00:00:00Z'),
    stripe_id: null,
    payment_method_id: null,
    full_name: 'Grace Lee',
    email: 'grace.lee@example.com',
    password: 'password123',
    is_verified: true,
    filled_profile_step: 5,
    otp_code: '321654',
    user_status: EUserStatus.ACTIVE,
    is_deleted_by_admin: false,
    user_role: EUserRole.BUYER,
    avatar: null,
    phone: '7788990011',
    address: '606 Willow St',
    address_2: null,
    country: 'Canada',
    city: 'Tokyo',
    cloth_size: 'M',
    jeans_size: 'L',
    shoes_size: 6,
  },
  {
    id: '9',
    created_at: new Date('2023-01-09T00:00:00Z'),
    updated_at: new Date('2023-01-09T00:00:00Z'),
    stripe_id: null,
    payment_method_id: null,
    full_name: 'Hank Young',
    email: 'hank.young@example.com',
    password: 'password123',
    is_verified: true,
    filled_profile_step: 5,
    otp_code: null,
    user_status: EUserStatus.ACTIVE,
    is_deleted_by_admin: false,
    user_role: EUserRole.VENDOR,
    avatar: null,
    phone: '8899001122',
    address: '707 Ash St',
    address_2: null,
    country: 'Canada',
    city: 'Beijing',
    cloth_size: 'L',
    jeans_size: 'XL',
    shoes_size: 9,
  },
];
