export const order_id_seed = 'order';
export const product_id_seed = 'product';
export const number_of_products = 1000;
export const number_of_orders = 1000;

export const vendor_ids = [
  '8a7d3b5a-2d4e-4f6a-8a3e-7b6d5f3e5a6d',
  '6d3b4f5a-2e4d-4a7e-9b3d-8a3b5d3e5a7e',
  '5d4a7b3e-2f6d-4a3b-8e7d-9b6a5d4e3a7e',
  '4a7d3b5e-2d6e-4f8a-9b7d-8a3b5d6e4a7e',
  '9b3d5a7e-2e6d-4f8b-8a3e-7d6b5a3e4a7e',
];

export const buyer_ids = [
  '8a6e0804-2bd0-4672-b79d-d97027f9071a',
  'e7d3e89a-2b3d-4f7d-880e-bf8299fbf5b3',
  'cfe48439-5b61-4e2e-8a7d-9a5d7e2e93df',
  '5b7d087c-3d5d-43f0-8a3b-5e1e3d5b3a5d',
  '1a7e8f4a-6d3d-49e7-9a3b-6d3b5d3a6b7e',
];

export const product_categories = [
  'T-shirts',
  'Jeans',
  'Dresses',
  'Shirts',
  'Tops',
  'Pants',
  'Coats',
  'Underwear',
];

export const lorem_description =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

export const fake_product_creation_date = '2022-01-01';

export const products_quantity = 1000;
export const orders_quantity = 1000;
export const max_price = 1000;
export const min_price = 1000;

export const product_names = [
  'Classic Cotton Tee',
  'Slim Fit Jeans',
  'Summer Floral Dress',
  'Casual Button-Down Shirt',
  'Sleeveless Tank Top',
  'Chino Pants',
  'Winter Wool Coat',
  'Comfort Fit Boxer Briefs',
  'Graphic T-shirt',
  'High-Waisted Skinny Jeans',
  'Basic White T-shirt',
  'Graphic Print T-shirt',
  'Striped T-shirt',
  'V-neck T-shirt',
  'Long Sleeve T-shirt',
  'Pocket T-shirt',
  'Crew Neck T-shirt',
  'Oversized T-shirt',
  'Slim Fit T-shirt',
  'Sport T-shirt',
  'Skinny Jeans',
  'Straight Leg Jeans',
  'Bootcut Jeans',
  'High Waisted Jeans',
  'Distressed Jeans',
  'Boyfriend Jeans',
  'Stretch Jeans',
  'Flare Jeans',
  'Wide Leg Jeans',
  'Cropped Jeans',
  'Summer Dress',
  'Maxi Dress',
  'Midi Dress',
  'Mini Dress',
  'Wrap Dress',
  'Bodycon Dress',
  'A-line Dress',
  'Shift Dress',
  'Off-shoulder Dress',
  'Cocktail Dress',
  'Formal Shirt',
  'Casual Shirt',
  'Linen Shirt',
  'Denim Shirt',
  'Plaid Shirt',
  'Oxford Shirt',
  'Flannel Shirt',
  'Hawaiian Shirt',
  'Chambray Shirt',
  'Button Down Shirt',
  'Tank Top',
  'Crop Top',
  'Blouse Top',
  'Tube Top',
  'Peplum Top',
  'Camisole Top',
  'Halter Top',
  'Sleeveless Top',
  'Ruffle Top',
  'Wrap Top',
  'Chino Pants',
  'Cargo Pants',
  'Sweatpants',
  'Jogger Pants',
  'Dress Pants',
  'Khaki Pants',
  'Corduroy Pants',
  'Leggings',
  'Yoga Pants',
  'Wide Leg Pants',
  'Trench Coat',
  'Peacoat',
  'Parka Coat',
  'Bomber Jacket',
  'Denim Jacket',
  'Leather Jacket',
  'Raincoat',
  'Windbreaker',
  'Down Coat',
  'Wool Coat',
  'Boxer Shorts',
  'Briefs',
  'Trunks',
  'Boxer Briefs',
  'Bikini Underwear',
  'Thong Underwear',
  'Hipster Underwear',
  'Seamless Underwear',
  'High Waisted Underwear',
  'Lace Underwear',
  'Sweater',
  'Hoodie',
  'Cardigan',
  'Pullover',
  'Crew Neck Sweater',
  'V-neck Sweater',
  'Turtleneck Sweater',
  'Zipper Hoodie',
  'Open Front Cardigan',
  'Sweater Vest',
];
